language: ruby

rvm:
  - 2.2

script:
  - bundle exec jekyll build

branches:
  except:
  - master

before_install:
  - gem install bundler
  - bundle install

deploy:
  provider: script
  script: "./_scripts/deploy.sh"
  skip_cleanup: false
  on:
    branch: source

